### ISSUE TITLE
Container  images sizeBytes to large to fit into Int, causing decode error

### ISSUE THREAD

**Issue by sbrunk** [hnaderi/scala-k8s#154]
Hi,

I've just tried to list nodes from a cluster via the API like this:

```scala
val client = SttpJdkURLClientBuilder.from("http://localhost:8001")
val nodes = APIs.nodes.list().send(client)
```

Triggering the following error:
```
...
dev.hnaderi.k8s.client.SttpKBackend$DecodeError: Expected Integer, but got: 3241619679
```

Looking at the original api server output, I think in this specific case it is the `sizeBytes` field in generated `ContainerImage`, but there might be other fields as well, that should use `Long` instead of `Int`.

```scala
final case class ContainerImage(
  names : Option[Seq[String]] = None,
  sizeBytes : Option[Int] = None
) {
...
```

**Comment by hnaderi** [comment]
Thank you for the bug report and also the pointer!
I'm investigating the problem...

**Comment by hnaderi** [comment]
Found the problem!
Apparently, there's an inconsistency in the k8s specification for numeric values or at least the code generation for numeric values does take these into account.
I'll push a fix soon.

**Comment by sbrunk** [comment]
Awesome! Thanks for looking into it @hnaderi

**Comment by hnaderi** [comment]
@sbrunk You can use the following in order to use the fixed version (after the CI publishes snapshots).
I also cut a release in a couple of days probably.
```scala
ThisBuild / resolvers ++= Resolver.sonatypeOssRepos("snapshots")
libraryDependencies ++= Seq(
  "dev.hnaderi" %% "scala-k8s-sttp" % "0.13-f42cd6c-SNAPSHOT"
)
```

**Comment by sbrunk** [comment]
Thanks @hnaderi for the fix. I just did a test run with the snapshot and I can confirm it's working now.
