### ISSUE TITLE
fieldSelector not working

### ISSUE THREAD

**Issue by thinkiny** [hnaderi/scala-k8s#199]
I use the code below to watch pod changes, seems like fieldSelector donesn't work, can you help ?

``` scala
fs2.Stream
      .resource(buildClient)
      .flatMap(
        CoreV1.events
          .list(fieldSelector = List(s"metadata.namespace=${ns}"))
          .listen
      )
```

**Comment by thinkiny** [comment]
this works :)

```scala
  fs2.Stream
      .resource(buildClient)
      .flatMap:
        EventAPI(ns).list.listen
```

**Comment by hnaderi** [comment]
What's the behavior?
By the way, you can use the namespace listen if you want to do that.
```scala
APIs
  .namespace(ns)
  .pods
  .listen
```

**Comment by thinkiny** [comment]
just watch all events under specific namespace

**Comment by hnaderi** [comment]
@thinkiny No, I mean the wrong behavior, e.g. it ends without result, waits indefinitely.
How does it behave when it doesn't work?
Also, have you also checked with `kubectl`?
In your first example, the cluster wide API is used, which k8s might ignore some of the filters, as these are dynamic based on the resource. Have you checked it?

**Comment by thinkiny** [comment]
ok, I get it,thanks
